const nodemailer = require("nodemailer");
const Moment = require("moment");
const EmailLog = require("../models/EmailLog");
const dev = process.env.NODE_ENV !== "production";
const getSlug = require("speakingurl");

const host = "web1010.dataplugs.com";
const port = 465;
const user = dev
  ? process.env.EMAIL_ACCOUNT_TEST
  : process.env.EMAIL_ACCOUNT_LIVE;
const pass = dev
  ? process.env.EMAIL_PASSWORD_TEST
  : process.env.EMAIL_PASSWORD_LIVE;
const rootUrl = dev ? process.env.ROOT_URL_TEST : process.env.ROOT_URL_LIVE;
const from = '"Tinkerer Box" <noreply@tinkererbox.com>';

const tableMaxWidth = "600px";

const htmlHeader = `
<table border='0' cellspacing='0' cellpadding='0' width='100%' bgcolor='#f5f5f5'><tbody><tr><td>
<table border='0' cellspacing='0' cellpadding='0'>
  <tbody>
      <tr><td height='40'></td></tr>
  </tbody>
</table>
<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#f07219;'>
  <tbody>
      <tr><td align='center'><img src='https://www.tinkererbox.com/static/steam/images/renewemail/header.png' style='max-width:600px;width:100%;' /></td></tr>
  </tbody>
</table>
    `;
const htmlFooter = `
<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;font-size:14px;'>
  <tbody>
    <tr><td align='center' style='padding: 15px 20px; text-align:center;'><span style='font-size:12px;font-style:italic;'>Subscription will be automatically renewed on the 1st day of the month after you have received the last box from your current subscription. You can cancel a recurring subscription from three days after you place the order in MY ACCOUNT. Please cancel at least three days before the auto-renewal date.</span></td></tr>
    <tr><td align='center' style='padding: 15px 0; text-align:center;'><span>This email is automatically generated by system.<br/>Please do not reply to this email.</span></td></tr>
    <tr><td align='center' style='text-align:center;'><a href='https://facebook.com/tinkererbox' target='_blank'><img src='https://www.tinkererbox.com/static/steam/images/socialmedia/fb.png' style='margin-right:10px;width:25px;height:25px;'/></a><a href="https://www.instagram.com/tinkerersteambox" target='_blank'><img src='https://www.tinkererbox.com/static/steam/images/socialmedia/ig.png' style='margin-right:10px;width:25px;height:25px;'/></a><a href="https://www.youtube.com/channel/UChHRTaGpiVjqv76YX3-O2dw" target='_blank'><img src='https://www.tinkererbox.com/static/steam/images/socialmedia/yt.png' style='width:25px;height:25px;'/></a></td></tr>
    <tr><td align='center' style='padding: 15px 0; text-align:center;'><a href='https://www.tinkererbox.com' target='_blank' style='color:#333333'>Tinkerer Site</a> | <a href='https://www.tinkererbox.com/#purchase-section' target='_blank' style='color:#333333'>Monthly Subscription</a> | <a href='https://www.tinkererbox.com/product-list' target='_blank' style='color:#333333'>Shop</a> | <a href='https://www.tinkererbox.com/contact' target='_blank' style='color:#333333'>Contact Us</a></td></tr>
    <tr><td align='center' style='padding-bottom: 15px; text-align:center;'>© ${Moment().format(
  "YYYY"
)} <a href='https://www.tinkererbox.com' target='_blank' style='color:#333333'>TINKERERBOX.COM</a> ALL RIGHTS RESERVED.</td></tr>
  </tbody>
</table>
</td></tr></tbody></table>
<p>${Moment().format("dddd, MMMM Do YYYY, h:mm:ss a")} End of message.</p>`;

const htmlHeaderCustom = `
<table border='0' cellspacing='0' cellpadding='0' width='600' bgcolor='#f5f5f5'><tbody><tr><td>
<table border='0' cellspacing='0' cellpadding='0'>
  <tbody>
      <tr><td height='40'></td></tr>
  </tbody>
</table>
<table border='0' cellspacing='0' cellpadding='0' width='600' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;margin-bottom:20px;'>
  <tbody>
      <tr><td align='center'><a href="https://tinkererbox.com" target='_blank'><img src='https://www.tinkererbox.com/static/steam/images/timg/logo_round.png' style='max-width:180px;width:100%;' width='180' /></a></td></tr>
  </tbody>
</table>
    `;
const htmlFooterCustom = `
<table border='0' cellspacing='0' cellpadding='0' width='600' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;font-size:14px;'>
  <tbody>
    <tr><td align='center' style='padding: 30px 20px 15px 20px; text-align:center;'><span style="line-height:25px;">Subscription will be automatically renewed on the 1st day of the month after you have received the last box from your current subscription. You can cancel a recurring subscription from three days after you place the order in MY ACCOUNT. Please cancel at least three days before the auto-renewal date.</span></td></tr>
    <tr><td align='center' style='padding: 15px 0; text-align:center;'><span style="line-height:25px;">This email is automatically generated by system.<br/>Please do not reply to this email.</span></td></tr>
    <tr><td align='center' style='text-align:center;padding: 15px 0;'><a href="https://tinkererbox.com/product-list" target='_blank'><img width='600' src='https://www.tinkererbox.com/static/steam/images/renewemail/tinkererbar.png' style="width:100%;"/></a></td></tr>
    <tr><td align='center' style='text-align:center;padding-bottom: 30px;'><a href='https://tinkererbox.com/product-list' target='_blank'><img width='130' src='https://www.tinkererbox.com/static/steam/images/renewemail/m1.png' style='Margin-left:10px;Margin-right:10px;margin-left:2.5%;margin-right:2.5%;max-width:130px;width:30%;'/></a>&nbsp;&nbsp;<a href="https://tinkererbox.com/product-list" target='_blank'><img width='130' hspace='10' src='https://www.tinkererbox.com/static/steam/images/renewemail/m2.png' style='Margin-right:10px;margin-right:2.5%;max-width:130px;width:30%;'/></a>&nbsp;&nbsp;<a href="https://tinkererbox.com/product-list" target='_blank'><img width='130' hspace='10' src='https://www.tinkererbox.com/static/steam/images/renewemail/m3.png' style='Margin-right:10px;margin-right:2.5%;max-width:130px;width:30%;'/></a></td></tr>
    <tr><td align='center' style='padding: 5px 0; text-align:center;'><a href='https://www.tinkererbox.com' target='_blank' style='color:#333333'>Tinkerer Site</a> | <a href='https://www.tinkererbox.com/#purchase-section' target='_blank' style='color:#333333'>Monthly Subscription</a> | <a href='https://www.tinkererbox.com/product-list' target='_blank' style='color:#333333'>Shop</a> | <a href='https://www.tinkererbox.com/contact' target='_blank' style='color:#333333'>Contact Us</a></td></tr>
    <tr><td align='center' style='padding-bottom: 35px; text-align:center;'>© ${Moment().format(
  "YYYY"
)} <a href='https://www.tinkererbox.com' target='_blank' style='color:#333333;text-decoration:none;'>TINKERERBOX.COM</a> ALL RIGHTS RESERVED.</td></tr>
    <tr><td align='center' style='text-align:center;padding-bottom: 30px;'><a href='https://facebook.com/tinkererbox' target='_blank'><img width='40' hspace='10' src='https://www.tinkererbox.com/static/steam/images/renewemail/fb.png' style='Margin-right:30px;margin-right:30px;width:40px;height:40px;'/></a>&nbsp;&nbsp;<a href="https://www.instagram.com/tinkerersteambox" target='_blank'><img width='40' hspace='10' src='https://www.tinkererbox.com/static/steam/images/renewemail/ig.png' style='Margin-right:30px;margin-right:30px;width:40px;height:40px;'/></a>&nbsp;&nbsp;<a href="https://www.youtube.com/channel/UChHRTaGpiVjqv76YX3-O2dw" target='_blank'><img width='40' hspace='10' src='https://www.tinkererbox.com/static/steam/images/renewemail/yt.png' style='width:40px;height:40px;'/></a></td></tr>
  </tbody>
</table>
</td></tr></tbody></table>
<p>${Moment().format("dddd, MMMM Do YYYY, h:mm:ss a")} End of message.</p>`;

const priceSign = `HKD $`;

// create reusable transporter object using the default SMTP transport
const transporter = nodemailer.createTransport({
  host,
  port,
  secure: true, // true for 465, false for other ports
  auth: {
    user,
    pass,
  },
});

function getCartProductTableRows({ cart, type }) {
  const priceSpan = `style='color:#f07213;font-weight:bold;'`;
  let cartTable = ``;
  const tableBody = `style='padding:10px;font-size:14px;color:#333333;background:#ffffff;border:1px solid #333333;vertical-align:middle;text-align:left;'`;
  cart.forEach((item) => {
    let productName = "";
    let qty = "";
    let totalPrice = "";
    if (item.product.data.productType != 1) {
      productName = item.product.data.name;
    }
    if (item.product.data.productType == 1) {
      if (item.product.subscription == false) {
        productName =
          item.product.data.category.title +
          " - " +
          item.product.data.detail.select +
          " Month Bundle";
      } else if (item.product.subscription == true) {
        productName =
          "<span style='color:#f07213;'>" +
          item.product.data.category.title +
          "</span>" +
          "<br/>" +
          item.product.data.detail.select +
          " Months Subscription";
      }
    }
    qty = item.product.qty;
    totalPrice = (item.product.data.price - item.product.data.discount) * qty;
    //console.log({ productName, qty, totalPrice });
    if (type == 1 || type == 10)
      cartTable += `<tr><td ${tableBody}><span style='vertical-align:middle;font-weight:500;'>${productName}</span></td><td ${tableBody}>${qty}</td><td ${tableBody}>${priceSign}<span ${priceSpan}>${totalPrice.toFixed(
        2
      )}</span></td></tr>`;
    else if (type == 3) {
      cartTable += `<tr><td ${tableBody}><span style='vertical-align:middle;font-weight:500;'>${productName}</span></td><td ${tableBody}>x ${qty}</td></tr>`;
    }
  });
  return cartTable;
}

function getDeliveryAddress(delivery) {
  let address = "";
  address += "<span>" + delivery.deliveryAddress.receiverName + "</span>";
  address += delivery.deliveryAddress.company
    ? "<br/><span>" + delivery.deliveryAddress.company + "</span>"
    : "";
  address += delivery.deliveryAddress.lineOne
    ? "<br/><span>" + delivery.deliveryAddress.lineOne + "</span>"
    : "";
  address += delivery.deliveryAddress.lineTwo
    ? "<br/><span>" + delivery.deliveryAddress.lineTwo + "</span>"
    : "";
  address += delivery.deliveryAddress.country
    ? "<br/><span>" + delivery.deliveryAddress.country + "</span>"
    : "";
  return address;
}

function getDeliveryProduct(delivery) {
  let product = "";
  if (delivery.item.product.data.productType == 0) {
    product =
      delivery.item.product.data.name + " Box x " + delivery.item.product.qty;
  }
  if (delivery.item.product.data.productType == 2) {
    product =
      delivery.item.product.data.name +
      " - " +
      "HKD $" +
      delivery.item.product.data.price;
  }
  if (
    delivery.item.product.data.productType == 1 &&
    delivery.item.product.data.detail.select &&
    delivery.item.product.selectedProduct
  ) {
    product =
      delivery.item.product.selectedProduct.name +
      " Box x " +
      delivery.item.product.qty;
  }
  return product;
}

function getPromotionProducts(promotionProducts) {
  let productStr = ``;
  for (let i = 0; i < promotionProducts.length; i++) {
    const product = promotionProducts[i];
    productStr += `<p style="margin-bottom:40px;margin-top:40px;border-bottom:2px dashed #f07213;"> </p>`;
    productStr += `<h2 style="color:#333333;">${product.name}</h2>`;
    productStr += `<p><img style="width:120px;" src="${`https://tinkererbox.com/static/steam/images/renewemail/${product.category.title}.png`}"/></p>`;
    productStr += `<p><img style="display:block;width:100%;max-width:600px;" src="${`https://tinkererbox.com/static/upload/${product.thumbnail[0].upload.folder}/${product.thumbnail[0].upload.fileName.current}`}"/></p>`;
    productStr += `<p style="color:#333333;margin-bottom:20px;">${product.description}</p>`;
    productStr += `<a href="https://tinkererbox.com/product-detail/${getSlug(
      product.name
    )}/${product._id
      }?fm=newproductemail" target="_blank" style="color:#fff;background:#f07213;padding:10px 30px;border-radius:20px;text-decoration:none;display:inline-block;">View More</a>`;
  }
  return productStr;
}

async function sendMail({
  userId, //required in most cases
  to, //required in most cases
  link,
  type, //required in all cases
  order,
  giftCard,
  cart,
  coupon,
  promotionEmail,
  getMailOnly,
  priceObj,
  delivery, //Delivery status changed to delivered
  subscriptionRenewObj,
  subscription,
  promotionProducts,
  user,
  months,
  deliveryArray,
  emailContent,
  title,
}) {
  try {
    let html = "";
    let mailOptions = { from, to };
    switch (type) {
      case 0: //send authenticate email to registered user
        html = `<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#f07219;font-size:12px;'><tbody>
        <tr><td align='center' valign='top'><h2 style='color:#ffffff'>Welcome to Tinkerer</h2></td></tr>
        <tr><td align='center' valign='top'><h3 style='color:#ffffff'>Click here to activate your account</h3></td></tr>
        <tr><td align='center' valign='top'><a href='${rootUrl + link
          }' target='_blank' style='padding:15px 25px;background:#2834d1;color:#ffffff;text-decoration:none;font-size:18px;border-radius:47px;display:inline-block'>Activate account</a></td></tr>
        <tr><td align='center' valign='top' height='20'></td></tr>
        </tbody></table>`;
        mailOptions.subject = "Tinkerer - Activate account";
        break;
      case 1: {
        //send order email to customer
        //send renew order email to customer
        const tableHeader = `style='padding:10px;font-size:14px;font-weight:bold;color:#333333;vertical-align:middle;text-align:left;'`;
        const priceSpan = `style='color:#f07213;font-weight:bold;'`;
        const cart = order.items;
        html = `
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;padding:20px 20px 10px 20px'><tbody>
          <tr><td>
          <h2 style='color:#333333;'>Hello ${order.username},</h2>
          <h3 style='color:#f07213;margin-bottom:0;font-size:15px;'>Thank you for shopping at TINKERER.COM</h3>
          <h3 style='color:#333333;padding-bottom:20px;border-bottom:2px solid #f07213;margin-top:0;margin-bottom:0;font-size:14px;'>For subscriptions, first box ships within 7 days and then on mid of each month. For others, they will ship within 7 days.</h3>
          </td></tr>
          </tbody></table>
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;padding:0px 20px 20px 20px'><tbody>
          <tr><td style='width:30%' valign='top'><h3 style='margin-bottom:0;font-size:14px;'>AMOUNT</h3><p style='margin-top:5px;font-size:14px;'>${priceSign}${parseFloat(
          order.totalAmount * 0.01
        ).toFixed(
          2
        )}</p></td><td style='width:40%' valign='top'><h3 style='margin-bottom:0;font-size:14px;'>DATE</h3><p style='margin-top:5px;font-size:14px;'>${Moment(
          order.created_at
        ).format(
          "MMMM DD[,]YYYY"
        )}</p></td><td style='width:30%' valign='top'><h3 style='margin-bottom:0;font-size:14px;'>PAYMENT</h3><p style='margin-top:5px;font-size:14px;'>${order.stripeCharge
            ? String(
              order.stripeCharge.payment_method_details.card.brand
            ).toUpperCase() +
            "-" +
            order.stripeCharge.payment_method_details.card.last4
            : "-"
          }</p></td></tr>
          </tbody></table>
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;padding:0px 20px 20px 20px'><tbody><tr><td>
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;border-collapse:collapse;background:#ffffff;'><tbody>
          <tr><td ${tableHeader} width='55'>Item</td><td ${tableHeader} width='15'>Qty</td><td ${tableHeader} width='30'>Price</td></tr>
          ${getCartProductTableRows({ cart, type })}
          ${`
          <tr style='font-size:14px;font-weight:bold;'><td colspan='2' style='text-align:right;padding:40px 0 10px 10px;'>Subtotal:</td><td style='text-align:left;padding:40px 10px 10px 10px;'>${priceSign}<span ${priceSpan}>${parseFloat(
            order.subtotal * 0.01
          ).toFixed(2)}</span></td></tr>
          <tr style='font-size:14px;font-weight:bold;'><td colspan='2' style='text-align:right;padding:0 0 10px 10px;'>Shipping:</td><td style='text-align:left;padding:0 10px 10px 10px;'>${priceSign}<span ${priceSpan}>${parseFloat(
            priceObj.deliverPriceTotal
          ).toFixed(2)}</span></td></tr>`}
          ${order.subtotal +
            priceObj.deliverPriceTotal * 100 -
            order.totalAmount !=
            0
            ? `<tr style='font-size:14px;font-weight:bold;'><td colspan='2' style='text-align:right;padding:0 0 10px 10px;'>Discount:</td><td style='text-align:left;padding:0 10px 10px 10px;'>${priceSign}<span ${priceSpan}>${parseFloat(
              (order.subtotal +
                priceObj.deliverPriceTotal * 100 -
                order.totalAmount) *
              0.01
            ).toFixed(2)}</span></td></tr>
          `
            : ``
          }
          <tr style='font-size:14px;font-weight:bold;'><td colspan='2' style='text-align:right;padding:0 0 10px 10px;'>Total:</td><td style='text-align:left;padding:0 10px 10px 10px;'>${priceSign}<span ${priceSpan}>${parseFloat(
            order.totalAmount * 0.01
          ).toFixed(2)}</span></td></tr>
          </tbody></table>
          </td></tr></tbody></table>`;
        mailOptions.subject = "Tinkerer - Purchase Order";
        break;
      }
      case 2: //send gift card email to receiver
        html = `<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#f07219;font-size:12px;'><tbody>
        <tr><td align='center' valign='top'><h2 style='color:#ffffff'>${giftCard.mail.content
          }</h2></td></tr>
        <tr><td align='center' valign='top'><h3 style='color:#ffffff;margin-bottom:0;'>Redeem Code</h3></td></tr>
        <tr><td align='center' valign='top'><span style='display:inline-block;padding:10px 20px;background:#f2f2f2;color:#333;'>${giftCard.code
          }</span></td></tr>
        <tr><td align='center' valign='top'><h3 style='color:#ffffff;margin-top:0;'>Worth: ${priceSign + parseFloat(giftCard.mail.giftCardAmount).toFixed(2)
          }<br/>Sent from: ${giftCard.mail.giverName}</h3></td></tr>
        <tr><td align='center' valign='top'><h3 style='color:#ffffff'>Enter the redeem code on our website.<br/><a href='${rootUrl + link
          }' target='_blank' style='color:#fff'>TINKERERBOX.COM</a></h3></td></tr>
        <tr><td align='center' valign='top' height='20'></td></tr>
        </tbody></table>`;
        mailOptions.subject = giftCard.mail.title;
        break;
      case 3: {
        //abandon cart promotion email, return only;
        //const couponDescription = coupon.description.replace(/\r\n/g,"<br/>");
        const tableHeader = `style='padding:10px;font-size:14px;font-weight:bold;color:#ffffff;vertical-align:middle;text-align:left;'`;
        html = `
        <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;border:2px solid #f07219;background:#ffffff;'><tbody>
        <h2 style='text-align:center;color:#f07219;margin:0;padding:10px 0;'>Discount is applied to your cart automatically!</h2>
        </tbody></table>
        <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;border-collapse:collapse;border:2px solid #f07219;background:#ffffff;'><tbody>
        <tr style='background-color:#f07219;'><td ${tableHeader}>Item</td><td ${tableHeader} width='40'>Qty</td></tr>
        ${getCartProductTableRows({ cart, type })}
        </tbody></table>
        <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;'><tbody>
        <tr><td align='center' valign='top' style="padding:15px 0"><a href='${rootUrl + "/cart"
          }' target='_blank' style='padding:15px 25px;background:#be4ca5;color:#ffffff;text-decoration:none;font-size:18px;border-radius:5px;display:inline-block'>Checkout Now</a></td></tr>
        <tr><td align='center' style='padding: 15px 0; text-align:center;color:#333;font-weight:bold;font-size:15px;'><span>${coupon.description.replace(
            /\r\n/g,
            "<br/>"
          )}</span></td></tr>
        </tbody></table>`;
        mailOptions.subject = "Discount for your cart - Tinkererbox.com";
        break;
      }
      case 4: //coupon promotion email, return only;
        html = `<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#f07219;font-size:12px;'><tbody>
        <tr><td align='center' valign='top'><p style='color:#ffffff;font-size:20px;'>Coupon Code</p></td></tr>
        <tr><td align='center' valign='top'><span style='display:inline-block;padding:10px 20px;background:#f2f2f2;color:#333;font-weight:bold;font-size:15px;'>${coupon.code
          }</span></td></tr>
        <tr><td align='center' style='padding: 15px 0; text-align:center;color:#333;font-weight:bold;font-size:15px;'><span>${coupon.description.replace(
            /\r\n/g,
            "<br/>"
          )}</span></td></tr>
        <tr><td align='center' valign='top'><p style='color:#ffffff;font-size:15px'>Enter the redeem code on our website.<br/><a href='${rootUrl + link
          }' target='_blank' style='color:#fff'>TINKERERBOX.COM</a></p></td></tr>
        <tr><td align='center' valign='top' height='20'></td></tr>
        </tbody></table>`;
        mailOptions.subject = "Coupon for your next purchase - Tinkererbox.com";
        break;
      case 5: //promotion email
        mailOptions = promotionEmail;
        html = promotionEmail.html;
        break;
      case 6: //send forget password email to user
        html = `<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#f07219;font-size:12px;'><tbody>
      <tr><td align='center' valign='top'><h2 style='color:#ffffff'>Reset Password</h2></td></tr>
      <tr><td align='center' valign='top'><h3 style='color:#ffffff'>Click here to reset your password</h3></td></tr>
      <tr><td align='center' valign='top'><a href='${rootUrl + link
          }' target='_blank' style='padding:15px 25px;background:#2834d1;color:#ffffff;text-decoration:none;font-size:18px;border-radius:47px;display:inline-block'>Reset password</a></td></tr>
      <tr><td align='center' valign='top' height='20'></td></tr>
      </tbody></table>`;
        mailOptions.subject = "Tinkerer - Reset Password";
        break;
      case 7: //send delivered email to user
        html = `<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#ffffff;font-size:12px;'><tbody>
        <tr><td align='center'><p style='padding:20px 5px;margin:0;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_box.jpg' style='max-width:200px' /></p></td></tr>
        <tr><td align='center'><h1 style='color:#f07213;padding:0 5px;margin:0;'>Your box has been shipped!</h1></td></tr>
        <tr><td align='left' valign='top'><h2 style='color:#333333;padding:0 20px;'>Hello ${delivery.user.name
          }</h2></td></tr>
      <tr><td align='left' valign='top'><p style='color:#333333;font-size:14px;padding:0 20px;margin-top:0;'>Your box has been shipped. We hope it brings you plenty of joy!<br/>If you have any questions, please contact us at <a style="color:#357087;" href="mailto:customercare@tinkererbox.com">customercare@tinkererbox.com</a></p></td></tr>
      <tr>
          <td style='padding:0 20px;'>
            <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#ffffff;font-size:12px;'><tbody>
              <tr>
                <td align='left' valign='top' style='background:#e1fbff;width:48%;border-radius:5px;overflow:hidden;'>
                  <h2 style='color:#ffffff;font-size:16px;margin:0;text-align:center;background:#357087;font-weight:500;padding:5px;'>Delivery Address:</h2>
                  <h3 style='color:#333333;font-size:14px;padding:10px;margin:0;font-weight:500;'>${getDeliveryAddress(
            delivery
          )}</h3>
                </td>
                <td align='left' valign='top' style='background:#ffffff;width:4%;'>
                </td>
                <td align='left' valign='top' style='background:#e1fbff;width:48%;border-radius:5px;overflow:hidden;'>
                  <h2 style='color:#ffffff;font-size:16px;margin:0;text-align:center;background:#357087;font-weight:500;padding:5px;'>Delivery Items:</h2>
                  <h3 style='color:#333333;font-size:14px;padding:10px;margin:0;font-weight:500;'>${getDeliveryProduct(
            delivery
          )}</h3>
                </td>
              </tr>
            </tbody></table>
          </td>
      </tr>
      <tr><td align='left' valign='top'><h3 style='color:#333333;font-size:14px;padding:0 20px 10px 20px;font-weight:500;border-bottom:4px dotted #f07213;'>${delivery.tracking && delivery.tracking.code
            ? "<span style='padding:5px 10px;border-radius:5px;color:#ffffff;background-color:#357087'>" +
            delivery.tracking.company +
            " tracking: " +
            delivery.tracking.code +
            "</span><br/><br/>"
            : ""
          }Happy tinkerering!<br/>The Tinkerer Team</h3></td></tr>
      <tr>
        <td style='padding:0 20px;'>
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#ffffff;font-size:12px;'><tbody>
            <tr>
            <td align='center' valign='middle' style='width:60px;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_icon_1.png' style='max-width:40px' /></td>
            <td align='left' valign='top' style='width:auto;'><p style='color:#333333;font-size:14px;padding:0 20px;'>Refer a friend to get <span style='color:#f07213;'>$50 HKD reward</span> for you and your friend. View details at:<br/><a style="color:#357087;" href='https://www.tinkererbox.com/how-referral-works' target='_blank'>https://www.tinkererbox.com/how-referral-works</a></p></td>
            </tr>
            <tr>
            <td align='center' valign='middle' style='width:60px;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_icon_2.png' style='max-width:40px' /></td>
            <td align='left' valign='top' style='width:auto;'><p style='color:#333333;font-size:14px;padding:0 20px;'>While waiting for your Tinkerer STEAM Box, keep posted on our cool designs on facebook:<br/><a style="color:#357087;" href='https://facebook.com/tinkererbox' target='_blank'>https://facebook.com/tinkererbox</a></p></td>
            </tr>
            <tr>
            <td align='center' valign='middle' style='width:60px;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_icon_3.png' style='max-width:40px' /></td>
            <td align='left' valign='top' style='width:auto;'><p style='color:#333333;font-size:14px;padding:0 20px;'>Share your fun moments with us! If your photos or videos get selected for our social media, we will send you a special gift. Send your fun moments to:<br/><a style="color:#357087;" href="mailto:media@tinkererbox.com">media@tinkererbox.com</a></p></td>
            </tr>
          </tbody></table>
        </td>
      </tr>
      <tr><td align='left' valign='top' height='20'></td></tr>
      </tbody></table>`;
        mailOptions.subject = "Tinkerer - Your order has been shipped!";
        break;
      case 701: //send delivered email to user
        html = `<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#ffffff;font-size:12px;'><tbody>
        <tr><td align='center'><p style='padding:20px 5px;margin:0;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_box.jpg' style='max-width:200px' /></p></td></tr>
        <tr><td align='center'><h1 style='color:#f07213;padding:0 5px;margin:0;'>Your box has been shipped!</h1></td></tr>
        <tr><td align='left' valign='top'><h2 style='color:#333333;padding:0 20px;'>Hello ${deliveryArray[0].user.name
          }</h2></td></tr>
      <tr><td align='left' valign='top'><p style='color:#333333;font-size:14px;padding:0 20px;margin-top:0;'>Your box has been shipped. We hope it brings you plenty of joy!<br/>If you have any questions, please contact us at <a style="color:#357087;" href="mailto:customercare@tinkererbox.com">customercare@tinkererbox.com</a></p></td></tr>
      <tr>
          <td style='padding:0 20px;'>
            <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#ffffff;font-size:12px;'><tbody>
              <tr>
                <td align='left' valign='top' style='background:#e1fbff;width:48%;border-radius:5px;overflow:hidden;'>
                  <h2 style='color:#ffffff;font-size:16px;margin:0;text-align:center;background:#357087;font-weight:500;padding:5px;'>Delivery Address:</h2>
                  <h3 style='color:#333333;font-size:14px;padding:10px;margin:0;font-weight:500;'>${getDeliveryAddress(
            deliveryArray[0]
          )}</h3>
                </td>
                <td align='left' valign='top' style='background:#ffffff;width:4%;'>
                </td>
                <td align='left' valign='top' style='background:#e1fbff;width:48%;border-radius:5px;overflow:hidden;'>
                  <h2 style='color:#ffffff;font-size:16px;margin:0;text-align:center;background:#357087;font-weight:500;padding:5px;'>Delivery Items:</h2>
                  <h3 style='color:#333333;font-size:14px;padding:10px;margin:0;font-weight:500;'>${deliveryArray
            .map(
              (delivery) =>
                `<span style='color:#333333;'>${getDeliveryProduct(
                  delivery
                )}<br/></span>`
            )
            .join("")}</h3>
                </td>
              </tr>
            </tbody></table>
          </td>
      </tr>
      <tr><td align='left' valign='top'><h3 style='color:#333333;font-size:14px;padding:0 20px 10px 20px;font-weight:500;border-bottom:4px dotted #f07213;'>${deliveryArray[0].tracking && deliveryArray[0].tracking.code
            ? "<span style='padding:5px 10px;border-radius:5px;color:#ffffff;background-color:#357087'>" +
            deliveryArray[0].tracking.company +
            " tracking: " +
            deliveryArray[0].tracking.code +
            "</span><br/><br/>"
            : ""
          }Happy tinkerering!<br/>The Tinkerer Team</h3></td></tr>
      <tr>
        <td style='padding:0 20px;'>
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#ffffff;font-size:12px;'><tbody>
            <tr>
            <td align='center' valign='middle' style='width:60px;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_icon_1.png' style='max-width:40px' /></td>
            <td align='left' valign='top' style='width:auto;'><p style='color:#333333;font-size:14px;padding:0 20px;'>Refer a friend to get <span style='color:#f07213;'>$50 HKD reward</span> for you and your friend. View details at:<br/><a style="color:#357087;" href='https://www.tinkererbox.com/how-referral-works' target='_blank'>https://www.tinkererbox.com/how-referral-works</a></p></td>
            </tr>
            <tr>
            <td align='center' valign='middle' style='width:60px;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_icon_2.png' style='max-width:40px' /></td>
            <td align='left' valign='top' style='width:auto;'><p style='color:#333333;font-size:14px;padding:0 20px;'>While waiting for your Tinkerer STEAM Box, keep posted on our cool designs on facebook:<br/><a style="color:#357087;" href='https://facebook.com/tinkererbox' target='_blank'>https://facebook.com/tinkererbox</a></p></td>
            </tr>
            <tr>
            <td align='center' valign='middle' style='width:60px;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_icon_3.png' style='max-width:40px' /></td>
            <td align='left' valign='top' style='width:auto;'><p style='color:#333333;font-size:14px;padding:0 20px;'>Share your fun moments with us! If your photos or videos get selected for our social media, we will send you a special gift. Send your fun moments to:<br/><a style="color:#357087;" href="mailto:media@tinkererbox.com">media@tinkererbox.com</a></p></td>
            </tr>
          </tbody></table>
        </td>
      </tr>
      <tr><td align='left' valign='top' height='20'></td></tr>
      </tbody></table>`;
        mailOptions.subject = "Tinkerer - Your order has been shipped!";
        break;
      case 8: //send gift card email to buyer
        html = `<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#f07219;font-size:12px;'><tbody>
        <tr><td align='center' valign='top'><h3 style='color:#ffffff;margin-bottom:0;font-weight:500;'>Redeem Code</h3></td></tr>
        <tr><td align='center' valign='top'><span style='display:inline-block;padding:10px 20px;background:#f2f2f2;color:#333;'>${giftCard.code
          }</span></td></tr>
        <tr><td align='center' valign='top'><h3 style='color:#ffffff;margin-top:0;font-weight:500;'>Worth: ${priceSign + parseFloat(giftCard.mail.giftCardAmount).toFixed(2)
          }</h3></td></tr>
        <tr><td align='center' valign='top'><h3 style='color:#ffffff;font-weight:500;'>Redeem the shopping credit on our website.<br/><a href='${rootUrl + link
          }' target='_blank' style='color:#fff;font-weight:500;'>TINKERERBOX.COM</a></h3></td></tr>
        <tr><td align='center' valign='top' height='20'></td></tr>
        </tbody></table>`;
        mailOptions.subject = giftCard.mail.title;
        break;
      case 9: //renew subscription email notice
        html = `<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#ffffff;font-size:12px;'><tbody>
        <tr><td align='center' valign='top'><h2 style='color:#333333;margin:30px 0 5px 0;'>Dear ${subscriptionRenewObj.name
          },</h2></td></tr>
        <tr><td align='center' valign='top'><p style='color:#333333;max-width:80%;font-size:14px;padding-bottom:20px;margin-bottom:10px;border-bottom:2px solid #f27019;'>We hope our Tinkerer boxes have brought your family fun and joy, as well as given your children new ways to express their creativity!</p></td></tr>
        <tr><td align='center' valign='top'><img src='https://www.tinkererbox.com/static/steam/images/renewemail/${String(
            subscriptionRenewObj.plan
          ).toLowerCase()}_${subscriptionRenewObj.planLength
          }.png' style='width:170px;margin-left:20px;' /></td></tr>
        <tr><td align='center' valign='top'><p style='color:#333333;max-width:80%;font-size:14px;padding-bottom:20px;margin-top:30px;margin-bottom:10px;border-bottom:2px solid #f27019;'>This is a friendly reminder that your ${subscriptionRenewObj.plan
          } – ${subscriptionRenewObj.planLength
          } Month <strong>subscription will be auto-renewed in 2 days.</strong> If you wish to stop receiving Tinkerer boxes, please go to your subscriptions in your account, and click on the link : ‘Cancel your subscription’.</p></td></tr>
        <tr><td align='center' valign='top'><img src='https://www.tinkererbox.com/static/steam/images/renewemail/credit.png' style='width:170px;margin-left:20px;' /></td></tr>
        <tr><td align='center' valign='top'><p style='color:#333333;max-width:80%;font-size:14px;margin-top:30px;'>When you <strong style="color:#f27019;">refer a friend</strong> to our subscription, both your friend and you will be <strong>credited HK$50</strong> (Tinkercoins). You can use your credit to purchase any items in our online store, or we will automatically deduct your Tinkercoins from your subscription payment.</p></td></tr>
        <tr><td align='center' valign='top'><p style='color:#333333;max-width:80%;font-size:14px;padding-bottom:20px;margin-top:10px;margin-bottom:0px;'><strong>Share the link: ${subscriptionRenewObj.referralLink
          }<br/>with your friend now via</strong></p></td></tr>
        <tr><td align='center' valign='top'><a href='https://wa.me/?text=${encodeURI(
            subscriptionRenewObj.referralLink
          )}' target="_blank"><img src='https://www.tinkererbox.com/static/steam/images/renewemail/whatsapp.png' style='width:30px;margin-right:30px;' /></a><a href='https://www.facebook.com/sharer/sharer.php?u=${encodeURI(
            subscriptionRenewObj.referralLink
          )}' target="_blank"><img src='https://www.tinkererbox.com/static/steam/images/renewemail/facebook.png' style='width:30px;margin-right:30px;' /></a><a href='mailto:?body=${encodeURI(
            subscriptionRenewObj.referralLink
          )}' target="_blank"><img src='https://www.tinkererbox.com/static/steam/images/renewemail/mail.png' style='width:30px;' /></a></td></tr>
        <tr><td align='center' valign='top'><p style='margin-bottom:30px;'></p></td></tr>
        </tbody></table>`;
        mailOptions.subject = "Tinkerer - Auto Renew";
        break;
      case 10: {
        //send renew order email to customer
        const tableHeader = `style='padding:10px;font-size:14px;font-weight:bold;color:#333333;vertical-align:middle;text-align:left;'`;
        const priceSpan = `style='color:#f07213;font-weight:bold;'`;
        const cart = order.items;
        html = `
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;padding:20px 20px 10px 20px'><tbody>
          <h2 style='color:#333333;'>Hello ${order.username},</h2>
          <h3 style='color:#f07213;margin-bottom:0;font-size:15px;'>Your subscription has been automatically renewed.</h3>
          <h3 style='color:#333333;padding-bottom:20px;border-bottom:2px solid #f07213;margin-top:0;margin-bottom:0;font-size:15px;'>We will despatch your box on 15th of each month.</h3>
          </tbody></table>
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;padding:0px 20px 20px 20px'><tbody>
          <tr><td style='width:30%' valign='top'><h3 style='margin-bottom:0;font-size:14px;'>AMOUNT</h3><p style='margin-top:5px;font-size:14px;'>${priceSign}${parseFloat(
          order.totalAmount * 0.01
        ).toFixed(
          2
        )}</p></td><td style='width:40%' valign='top'><h3 style='margin-bottom:0;font-size:14px;'>DATE</h3><p style='margin-top:5px;font-size:14px;'>${Moment(
          order.created_at
        ).format(
          "MMMM DD[,]YYYY"
        )}</p></td><td style='width:30%' valign='top'><h3 style='margin-bottom:0;font-size:14px;'>PAYMENT</h3><p style='margin-top:5px;font-size:14px;'>${String(
          order.stripeCharge.payment_method_details.card.brand
        ).toUpperCase() +
          "-" +
          order.stripeCharge.payment_method_details.card.last4
          }</p></td></tr>
          </tbody></table>
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;padding:0px 20px 20px 20px'><tbody><tr><td>
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;border-collapse:collapse;background:#ffffff;'><tbody>
          <tr><td ${tableHeader} width='55'>Item</td><td ${tableHeader} width='15'>Qty</td><td ${tableHeader} width='30'>Price</td></tr>
          ${getCartProductTableRows({ cart, type })}
          ${`
          <tr style='font-size:14px;font-weight:bold;'><td colspan='2' style='text-align:right;padding:40px 0 10px 10px;'>Subtotal:</td><td style='text-align:left;padding:40px 10px 10px 10px;'>${priceSign}<span ${priceSpan}>${parseFloat(
            order.subtotal * 0.01
          ).toFixed(2)}</span></td></tr>
          <tr style='font-size:14px;font-weight:bold;'><td colspan='2' style='text-align:right;padding:0 0 10px 10px;'>Shipping:</td><td style='text-align:left;padding:0 10px 10px 10px;'>${priceSign}<span ${priceSpan}>${parseFloat(
            priceObj.deliverPriceTotal
          ).toFixed(2)}</span></td></tr>`}
          ${order.subtotal +
            priceObj.deliverPriceTotal * 100 -
            order.totalAmount !=
            0
            ? `<tr style='font-size:14px;font-weight:bold;'><td colspan='2' style='text-align:right;padding:0 0 10px 10px;'>Discount:</td><td style='text-align:left;padding:0 10px 10px 10px;'>${priceSign}<span ${priceSpan}>${parseFloat(
              (order.subtotal +
                priceObj.deliverPriceTotal * 100 -
                order.totalAmount) *
              0.01
            ).toFixed(2)}</span></td></tr>
          `
            : ``
          }
          <tr style='font-size:14px;font-weight:bold;'><td colspan='2' style='text-align:right;padding:0 0 10px 10px;'>Total:</td><td style='text-align:left;padding:0 10px 10px 10px;'>${priceSign}<span ${priceSpan}>${parseFloat(
            order.totalAmount * 0.01
          ).toFixed(2)}</span></td></tr>
          </tbody></table>
          </td></tr></tbody></table>`;
        mailOptions.subject = "Tinkerer - Subscription Auto Renew";
        break;
      }
      case 11: {
        //send product feedback questionaire email
        html = `
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;padding:20px 20px 10px 20px'><tbody>
          <tr><td align='center'>
          <h2 style='color:#333333;text-align:center;'>Hi ${delivery.user.name
          },</h2>
          <p style='color:#333333;padding-bottom:20px;margin-top:0;margin-bottom:0;font-size:14px;text-align:center;'>This is Anthony from Tinkerer.<br/>We'd love to hear back from you on your Tinkerer experience so far.<br/>Tell us what you think by answering a few questions,<br/>and find out how to receive your free Tinkerer box.</p>
          <p style="color:#333333;text-align:center;"><img src="https://tinkererbox.com/static/steam/images/renewemail/free_box_img.png" style="max-width:300px"/></p>
          <p style="color:#333333;text-align:center;">Rate the <span style="font-weight:bold">${delivery.item.product.data.productType == 0
            ? delivery.item.product.data.name
            : delivery.item.product.selectedProduct.name
          }</span> box?</p>
          <p style="text-align:center;"><a href="https://tinkererbox.com/product-feedback/${delivery.id
          }/1/${delivery.feedbackSecret
          }"><img src="https://tinkererbox.com/static/steam/images/renewemail/star.png" style="width:35px"/></a><a href="https://tinkererbox.com/product-feedback/${delivery.id
          }/2/${delivery.feedbackSecret
          }"><img src="https://tinkererbox.com/static/steam/images/renewemail/star.png" style="width:35px"/></a><a href="https://tinkererbox.com/product-feedback/${delivery.id
          }/3/${delivery.feedbackSecret
          }"><img src="https://tinkererbox.com/static/steam/images/renewemail/star.png" style="width:35px"/></a><a href="https://tinkererbox.com/product-feedback/${delivery.id
          }/4/${delivery.feedbackSecret
          }"><img src="https://tinkererbox.com/static/steam/images/renewemail/star.png" style="width:35px"/></a><a href="https://tinkererbox.com/product-feedback/${delivery.id
          }/5/${delivery.feedbackSecret
          }"><img src="https://tinkererbox.com/static/steam/images/renewemail/star.png" style="width:35px"/></a></p>
          </td></tr>
          </tbody></table>`;
        mailOptions.subject = "Tinkerer - Help us improve with your feedback!";
        break;
      }
      case 12: {
        //send subscription cancelled questionaire email
        html = `
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;'><tbody>
          <tr><td align='center'>
          <img style="display:block;width:100%;" src="https://tinkererbox.com/static/steam/images/renewemail/subscription_cancelled_header.png"/>
          <h2 style='color:#333333;text-align:center;font-size:18px;'>Hi ${subscription.user.name},</h2>
          <p style="font-size:16px;">We are confirming that your subscription <strong>has been cancelled.</strong><br/>
          We are sorry that you are leaving us.</p>
          <h3 style="font-size:16px;">Thank you, once again for trying out our services.</h3>
          <p style="font-size:16px;">You can always come back whenever you want.<br/>
          Feel free to contact us at any time if you have any questions.<br/><br/>
          Tinkerer Team
          </p>
          </td></tr>
          </tbody></table>`;
        /*html = `
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;'><tbody>
          <tr><td align='center'>
          <img style="display:block;width:100%;" src="https://tinkererbox.com/static/steam/images/renewemail/subscription_cancelled_header.png"/>
          <h2 style='color:#333333;text-align:center;'>Hi ${subscription.user.name},</h2>
          <a href="${rootUrl}/cancel-subscription-feedback/${subscription._id}/${subscription.feedbackSecret}"><img style="display:block;width:100%;" src="https://tinkererbox.com/static/steam/images/renewemail/subscription_cancelled_text_1.png"/></a>
          </td></tr>
          </tbody></table>`;*/
        mailOptions.subject = "Tinkerer - We're Sorry to See You Go";
        break;
      }
      case 13: {
        //send product promotional email to user
        html = `
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;padding:20px 20px 10px 20px'><tbody>
          <tr><td align='center'>
          <h2 style='color:#333333;text-align:center;'>Hi ${user.name},</h2>
          <p style='color:#333333;margin-top:0;margin-bottom:0;font-size:14px;text-align:center;'>We Have Wonderful News!<br/>We have some exciting new boxes that need tinkering.<br/>Take a peek at the new boxes by following the link and find out more.</p>
          ${getPromotionProducts(promotionProducts)}
          <p style="margin-bottom:40px;"> </p>
          </td></tr>
          </tbody></table>`;
        mailOptions.subject = "Tinkerer - Exciting new products!";
        break;
      }
      case 14: {
        //send new year promotional email to user
        html = `
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;padding:20px 20px 10px 20px'><tbody>
          <tr><td align='center'>
          <h2 style='color:#333333;text-align:center;'>Hi ${user.name},</h2>
          <p style='color:#333333;text-align:center;font-size:16px;margin-bottom:20px;'>It is almost Chinese New Year and Tinkerer has an offer for you to celebrate.</p>
          </td></tr>
          <tr><td align='center'>
          <a href='${rootUrl}/product-list' target='_blank'><img style="display:block;width:100%;" src="https://tinkererbox.com/static/steam/images/renewemail/new_year_rat.png"/></a>
          </td></tr>
          <tr><td align='center'>
          <p style='color:#333333;text-align:center;font-weight:bold;font-size:16px;margin-bottom:20px;margin-top:20px;'>Receive 20% off your whole shopping cart with offer code: GOLDENRAT.</p>
          <p style='color:#333333;text-align:center;font-size:16px;margin-bottom:0;'>Hurry, this offer is for this weekend only,</p>
          <p style='color:#333333;text-align:center;font-size:16px;margin:0;'>starting tomorrow, Friday 17th January</p>
          <p style='color:#333333;text-align:center;font-size:16px;margin-bottom:20px;margin-top:0'>and ending on Monday 20th January.</p>
          <p style='color:#333333;text-align:center;font-size:16px;'>Follow the link to see all our products.</p>
          </td></tr>
          <tr><td align='center' valign='top'><a href='${rootUrl}/product-list' target='_blank' style='padding:15px 25px;background:#f07213;color:#ffffff;text-decoration:none;font-size:18px;border-radius:47px;display:inline-block'>Products</a></td></tr>
          <tr><td align='center'>
          <p style='color:#333333;text-align:center;font-weight:bold;font-size:16px;'>Happy Tinkerering!</p>
          </td></tr>
          </tbody></table>`;
        mailOptions.subject = "Tinkerer - Chinese New Year Offer!";
        break;
      }
      case 15: {
        //send delay email to user
        html = `
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;'><tbody>
          <tr><td align='center'>
          <img style="display:block;width:100%;" src="https://tinkererbox.com/static/steam/images/renewemail/subscription_suspension_header_new.png"/>
          <h2 style='color:#333333;text-align:center;'>Dear ${user.name},</h2>
          <p style='margin:0 20px;'>We regret to inform you that due to the outbreak of the coronavirus, we are unable to ship this month's subscription box to you.</p>
          <p style='padding: 20px 0px; margin: 0 20px; border-bottom: 2px solid #f07213;'>We are sorry if this cause any inconvenience or disappointment, but we hope that you understand the situation, due to the current circumstances.</p>
          <p style='margin: 20px;'>You will still receive <strong>all ${months} of the boxes</strong> that you have subscribed for, your box has been postponed by a month.</p>
          <p style='padding: 0 0 20px 0px; margin: 0 20px; border-bottom: 2px solid #f07213;'>If you have any questions please contact us on<br/>customercare@tinkererbox.com</p>
          <p style='margin: 20px;'>We hope that you and your family are staying safe through this time and we hope to help you tinker again soon!</p>
          <p style='margin: 0 20px 20px 20px;'>Kind Regards,<br/>
          Tinkerer Customer Care Team
          </p>
          </td></tr>
          </tbody></table>`;
        mailOptions.subject = "Tinkerer - Subscription suspension";
        break;
      }
      case 16: {
        //send general email from backend
        /*html = `
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;'><tbody>
          <tr><td style='padding:10px 10px;'>
          <h2 style='color:#333333;text-align:center;'>Hi ${user.name},</h2>
          ${emailContent}
          </td></tr>
          </tbody></table>`;*/
        html = `
          <table border='0' cellspacing='0' cellpadding='0' width='600' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;'><tbody>
          <tr><td style='padding:10px 10px;'>
          ${emailContent}
          </td></tr>
          </tbody></table>`;
        mailOptions.subject = title;
        break;
      }
      case 17: {
        //send return email to customer under development
        html = `<table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#ffffff;font-size:12px;'><tbody>
        <tr><td align='center'><p style='padding:20px 5px;margin:0;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_box.jpg' style='max-width:200px' /></p></td></tr>
        <tr><td align='center'><h1 style='color:#f07213;padding:0 5px;margin:0;'>Your box has been shipped!</h1></td></tr>
        <tr><td align='left' valign='top'><h2 style='color:#333333;padding:0 20px;'>Hello ${deliveryArray[0].user.name
          }</h2></td></tr>
      <tr><td align='left' valign='top'><p style='color:#333333;font-size:14px;padding:0 20px;margin-top:0;'>Your box has been shipped. We hope it brings you plenty of joy!<br/>If you have any questions, please contact us at <a style="color:#357087;" href="mailto:customercare@tinkererbox.com">customercare@tinkererbox.com</a></p></td></tr>
      <tr>
          <td style='padding:0 20px;'>
            <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#ffffff;font-size:12px;'><tbody>
              <tr>
                <td align='left' valign='top' style='background:#e1fbff;width:48%;border-radius:5px;overflow:hidden;'>
                  <h2 style='color:#ffffff;font-size:16px;margin:0;text-align:center;background:#357087;font-weight:500;padding:5px;'>Delivery Address:</h2>
                  <h3 style='color:#333333;font-size:14px;padding:10px;margin:0;font-weight:500;'>${getDeliveryAddress(
            deliveryArray[0]
          )}</h3>
                </td>
                <td align='left' valign='top' style='background:#ffffff;width:4%;'>
                </td>
                <td align='left' valign='top' style='background:#e1fbff;width:48%;border-radius:5px;overflow:hidden;'>
                  <h2 style='color:#ffffff;font-size:16px;margin:0;text-align:center;background:#357087;font-weight:500;padding:5px;'>Delivery Items:</h2>
                  <h3 style='color:#333333;font-size:14px;padding:10px;margin:0;font-weight:500;'>${deliveryArray
            .map(
              (delivery) =>
                `<span style='color:#333333;'>${getDeliveryProduct(
                  delivery
                )}<br/></span>`
            )
            .join("")}</h3>
                </td>
              </tr>
            </tbody></table>
          </td>
      </tr>
      <tr><td align='left' valign='top'><h3 style='color:#333333;font-size:14px;padding:0 20px 10px 20px;font-weight:500;border-bottom:4px dotted #f07213;'>${deliveryArray[0].tracking && deliveryArray[0].tracking.code
            ? "<span style='padding:5px 10px;border-radius:5px;color:#ffffff;background-color:#357087'>" +
            deliveryArray[0].tracking.company +
            " tracking: " +
            deliveryArray[0].tracking.code +
            "</span><br/><br/>"
            : ""
          }Happy tinkerering!<br/>The Tinkerer Team</h3></td></tr>
      <tr>
        <td style='padding:0 20px;'>
          <table border='0' cellspacing='0' cellpadding='0' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;background-color:#ffffff;font-size:12px;'><tbody>
            <tr>
            <td align='center' valign='middle' style='width:60px;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_icon_1.png' style='max-width:40px' /></td>
            <td align='left' valign='top' style='width:auto;'><p style='color:#333333;font-size:14px;padding:0 20px;'>Refer a friend to get <span style='color:#f07213;'>$50 HKD reward</span> for you and your friend. View details at:<br/><a style="color:#357087;" href='https://www.tinkererbox.com/how-referral-works' target='_blank'>https://www.tinkererbox.com/how-referral-works</a></p></td>
            </tr>
            <tr>
            <td align='center' valign='middle' style='width:60px;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_icon_2.png' style='max-width:40px' /></td>
            <td align='left' valign='top' style='width:auto;'><p style='color:#333333;font-size:14px;padding:0 20px;'>While waiting for your Tinkerer STEAM Box, keep posted on our cool designs on facebook:<br/><a style="color:#357087;" href='https://facebook.com/tinkererbox' target='_blank'>https://facebook.com/tinkererbox</a></p></td>
            </tr>
            <tr>
            <td align='center' valign='middle' style='width:60px;'><img src='https://www.tinkererbox.com/static/steam/images/socialpic/mail_icon_3.png' style='max-width:40px' /></td>
            <td align='left' valign='top' style='width:auto;'><p style='color:#333333;font-size:14px;padding:0 20px;'>Share your fun moments with us! If your photos or videos get selected for our social media, we will send you a special gift. Send your fun moments to:<br/><a style="color:#357087;" href="mailto:media@tinkererbox.com">media@tinkererbox.com</a></p></td>
            </tr>
          </tbody></table>
        </td>
      </tr>
      <tr><td align='left' valign='top' height='20'></td></tr>
      </tbody></table>`;
        mailOptions.subject = "Tinkerer - Your order has been shipped!";
        break;
      }
      case 18: {
        //send subscription add price email
        html = `
          <table border='0' cellspacing='0' cellpadding='0' width='600' style='font-family:"Open Sans",Arial;width:100%;max-width:${tableMaxWidth};margin-left:auto;margin-right:auto;color:#333333;background:#ffffff;'><tbody>
          <tr><td style='padding:10px 10px;'>
          <p style="text-align: center;"><span style="color: #000000;">Dear ${user.name},</span></p>
          <p style="text-align: center;"><span style="color: #000000;">We will be increasing our Tinkerer box retail price. The new price will be:</span></p>
          <table style="border-collapse: collapse; width: 100%; height: 189px;" border="1">
          <tbody>
          <tr style="height: 21px;">
          <td style="width: 33.3333%; text-align: center; height: 21px;">&nbsp;</td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">Per box price</span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">Total price</span></td>
          </tr>
          <tr style="height: 21px;">
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">Box</span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;"><strong>HKD 299</strong></span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">HKD 299</span></td>
          </tr>
          <tr style="height: 21px;">
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">Bundle-3</span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;"><strong>HKD 293</strong></span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">HKD 879</span></td>
          </tr>
          <tr style="height: 21px;">
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">Bundle-6</span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;"><strong>HKD 275</strong></span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">HKD 1650</span></td>
          </tr>
          <tr style="height: 21px;">
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">Bundle-12</span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;"><strong>HKD 254</strong></span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">HKD 3050</span></td>
          </tr>
          <tr style="height: 21px;">
          <td style="width: 33.3333%; text-align: center; height: 21px;">&nbsp;</td>
          <td style="width: 33.3333%; text-align: center; height: 21px;">&nbsp;</td>
          <td style="width: 33.3333%; text-align: center; height: 21px;">&nbsp;</td>
          </tr>
          <tr style="height: 21px;">
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">3M Subscription</span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;"><strong>HKD 254</strong></span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">HKD 762</span></td>
          </tr>
          <tr style="height: 21px;">
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">6M Subscription</span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;"><strong>HKD 239</strong></span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">HKD 1435</span></td>
          </tr>
          <tr style="height: 21px;">
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">12M Subscription </span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;"><strong>HKD 216</strong></span></td>
          <td style="width: 33.3333%; text-align: center; height: 21px;"><span style="color: #000000;">HKD 2598</span></td>
          </tr>
          </tbody>
          </table>
          <p style="text-align: center;"><span style="color: #000000;">Due to this, your next subscription fee will be calculated at our amended price.</span></p>
          <p style="text-align: center;"><span style="color: #000000;">You will still receive the rest of your boxes in your current subscription at the prepaid price.</span></p>
          <p style="text-align: center;"><span style="color: #000000;">However, when the time comes to auto-renew, your new subscription fee for <span style="color: #e67e23;"><strong>${user.months} months</strong></span> will be <span style="color: #e67e23;"><strong>HKD ${user.newPrice}</strong></span>.</span></p>
          <p style="text-align: center;"><span style="color: #000000;">If you have any questions or queries, please do not hesitate to contact our customer service team at <a style="color: #000000;" href="mailto:customercare@tinkererbox.com">customercare@tinkererbox.com</a></span></p>
          <p style="text-align: center;"><span style="color: #000000;">Tinkerer Team</span></p>
          </td></tr>
          </tbody></table>`;
        mailOptions.subject = "Tinkerer - Important Price Update!";
        break;
      }
      default:
        break;
    }
    if (getMailOnly === true) {
      mailOptions.html = html;
      return mailOptions; //return the mail content and exit function
    }
    if (html !== "") {
      if (type !== 16 && type !== 18) {
        mailOptions.html = htmlHeader + html + htmlFooter;
      } else {
        mailOptions.html = htmlHeaderCustom + html + htmlFooterCustom;
      }
      const sendResult = await transporter.sendMail(mailOptions);
      if (!promotionEmail && userId)
        EmailLog.create({
          user: userId,
          detail: mailOptions,
          result: sendResult,
        });
    }
    return true;
  } catch (e) {
    return false;
  }
}

module.exports = {
  sendMail,
};
